//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lelouch
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciler
    {
        public int id { get; set; }
        public string ogAdi { get; set; }
        public string ogSinifi { get; set; }
        public string ogNo { get; set; }
        public string ogTel { get; set; }
        public Nullable<bool> ogDurumu { get; set; }
    }
}
